# Generated by Django 5.2.4 on 2025-07-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(help_text='Name of the tag (bucket)')),
                ('tag_description', models.CharField(blank=True, help_text='Description of tag', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Image stored on the S3')),
                ('size', models.IntegerField(help_text='Size of asset (file) in bytes')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='wcms.wcmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.BooleanField(default=True)),
                ('description', models.CharField()),
                ('banner', models.CharField()),
                ('background', models.CharField()),
                ('bucket_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wcms.bucket')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='wcms.wcmsuser')),
                ('tags', models.ManyToManyField(related_name='buckets', to='wcms.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('porder', models.IntegerField()),
                ('public', models.BooleanField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wcms.bucket')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wcms.wcmsuser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.CharField(help_text='The text content of the comment', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wcms.wcmsuser')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='wcms.page')),
            ],
        ),
    ]
