# Generated by Django 5.2.4 on 2025-07-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0002_tag_asset_bucket_page_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='page_id',
        ),
        migrations.AddField(
            model_name='asset',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='wcms.page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucket',
            name='name',
            field=models.CharField(default='buzz', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='file_name',
            field=models.CharField(help_text='Image stored on the S3', max_length=255),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='background',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='banner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wcms.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_description',
            field=models.CharField(blank=True, help_text='Description of tag', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(help_text='Name of the tag (bucket)', max_length=100),
        ),
    ]
