# Generated by Django 5.2.4 on 2025-07-18 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0003_remove_asset_page_id_asset_page_bucket_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='readers',
            field=models.ManyToManyField(related_name='bucket_readers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='readers',
            field=models.ManyToManyField(related_name='readers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='bucket_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wcms.bucket'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(help_text='Name of the tag (bucket)', max_length=100, unique=True),
        ),
    ]
