# Generated by Django 5.2.4 on 2025-08-20 00:57

from django.db import migrations, models
from django.utils.text import slugify


def generate_bucket_slugs(apps, schema_editor):
    """Generate slugs for existing buckets"""
    Bucket = apps.get_model('wcms', 'Bucket')
    
    for bucket in Bucket.objects.all():
        # Generate a unique slug based on the name
        base_slug = slugify(bucket.name)
        if not base_slug:
            base_slug = 'bucket'
        
        slug = base_slug
        counter = 1
        
        # Keep trying until we find a unique slug
        while Bucket.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
            
        bucket.slug = slug
        bucket.save()


def reverse_generate_bucket_slugs(apps, schema_editor):
    """Reverse operation - clear all slugs"""
    Bucket = apps.get_model('wcms', 'Bucket')
    Bucket.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0004_bucket_readers_page_readers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='slug',
            field=models.SlugField(default='temp-slug', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            generate_bucket_slugs,
            reverse_generate_bucket_slugs,
        ),
    ]
