# Generated by Django 5.2.4 on 2025-08-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0006_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['page', 'file_name']},
        ),
        migrations.AlterModelOptions(
            name='bucket',
            options={'ordering': ['pk', 'name']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['page', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['bucket', 'porder', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.AlterField(
            model_name='bucket',
            name='background',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='buckets', to='wcms.tag'),
        ),
    ]
