# Generated by Django 5.2.4 on 2025-08-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0007_alter_asset_options_alter_bucket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='porder',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='page',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
