# Generated by Django 5.2.4 on 2025-08-20 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0008_alter_page_description_alter_page_porder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name='Revisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(help_text='Sequential revision number for this page')),
                ('diff', models.TextField(help_text='Unified diff or full content for first revision')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this revision was created')),
                ('page', models.ForeignKey(help_text='The page this revision belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wcms.page')),
            ],
            options={
                'verbose_name_plural': 'Revisions',
                'ordering': ['page', 'revision_number'],
                'unique_together': {('page', 'revision_number')},
            },
        ),
    ]
