# Generated by Django 5.2.4 on 2025-08-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0009_alter_page_description_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisions',
            name='diff',
            field=models.TextField(help_text='Full content of the page at this revision'),
        ),
    ]
