# Generated by Django 5.2.4 on 2025-08-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0010_update_revision_field_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='wcmsuser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
