# Generated by Django 5.2.5 on 2025-10-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0011_wcmsuser_firebase_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcmsuser',
            name='firebase_uid',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
