# Generated by Django 5.2.5 on 2025-10-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0012_alter_wcmsuser_firebase_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wcmsuser',
            name='firebase_uid',
        ),
        migrations.AlterField(
            model_name='wcmsuser',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
