# Generated by Django 5.2.5 on 2026-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0013_remove_wcmsuser_firebase_uid_alter_wcmsuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='pg_banner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='background',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='banner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
