# Generated by Django 5.2.5 on 2026-01-16 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0014_bucket_pg_banner_page_background_page_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['owner', 'file_name', 'size']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='page',
        ),
        migrations.AddField(
            model_name='asset',
            name='can_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
