# Generated by Django 5.2.5 on 2026-01-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcms', '0015_alter_asset_options_remove_asset_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='file_name',
            field=models.CharField(help_text='Image stored on the S3', max_length=255, unique=True),
        ),
    ]
